apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager-operated
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - alertmanager.kube.harish2k01.xyz
    secretName: alertmanager-tls
  rules:
  - host: alertmanager.kube.harish2k01.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alertmanager-operated
            port:
              number: 9093
