apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    discord-webhook-url: AgDDmYGK8YMHXJFEghMSi6YaVm/wvY/aF3KsD1RrIfZ4Dx9+D0drD0NEhaMouPbVznOcG4kW37wq1pyEWdXN2bUgqNaamTq+YyM326BOJJ22ZKPy5yyIN96nBVd7fwVsN2G0PUFLwuwz2UTDXSOwuhfFAnCTRHLBY496PqVqSNHHn2Y1qGGDECDWjNEonf5NtVZeuUZyvnNmVOikqqrpnR7U7KN7rK6rDHc0AGDRSsEEE9EIDBQl3KwfNPHDgiaP6AgUKkFFCpdxYjQOwKQ2JPxrjoOqg5Ff9sVjj03jKnhpk+WHrVHsl4HBFM+1rkDpf9WxN3vpVTIzk87Ip9KUYajYtcTeoIHa+rU8fyNrdqTDoSnPdo7ua6Pk7Qk7I0i4nAita6ojcntyKrxNtFoSmR1yTtPi9Rv7gVxnNvHtHw/CdhhS7Supo+0gZtHcUbGoMEQw450UbVEN0d4pamOVCYkW5KqohX3ayz7/Zpz6mGIHmbqZeA0Heg+Tgvsov3afUI6I9lh9WrqhOOJyFBtsPyW31FU2HKOrm1cjTO4a3nZ1u841NxOXVB0BotwQlSxfgZiO6rUqLqMdq9PB2bVVnP+Pqlcv1jcJ3KD4dUchoRzD2x4CXXaTI+DhpSwaNRjbfeUoipOFShwyc3mClGK1/ibSoA5e8qesUpMfY+ej7q7/JGzHbupKpNDW1ou06N14NsLSesPAFqeqVgPiLrXTvJ68WRv8anabnWKb5GpqqZZ3TBU1KJHR5IUzn17HEUem350K9hhzTiIl2jwgl6I7k0mBeCE2KNsSjdF/GYdTKN7Gyx5iVrZs/pP3iUQhxuUNYvO1SpA1uiSxr4n2feEZhL5HpHbeIYa5HjfoYpAH20W7
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
    type: Opaque