apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    discord-webhook-url: AgCTC5Vpmeo5wMfVtGxknV/R03AjC7xQHOaGA+JpHlqWSlzT2Pb8iXT39nuIJVV5fClsqpduyN999s1n3GKNPU15w6G6FhxPV9i+Wb9+YOA0YG48iXto8kGJUVqtdXLmKKgxBMyXWawCKj3i6TYjhwhv1Lj0it+WU0tjuVnMQy/E+sjfo31klQHeCA3gKt7lN3Vc2i3cknq8WiMix4Xc6eOhvpzrnzVyfjzqe9M1ZxtxwmvoohO3IXJHpzVhjUC2E0LeBJSpQiZWk43JtJT/y3MjRmI2OC6rfxjx7f19X3iCCe0ogdcttRMTTQPf4uCvSQTXRV5C7ozRi5Flyz4nuDkre+NH7nWxxoAAGk/pfQH/QMSzXCk9IjpZT4XSK/LwfXju5d0K5NLP9w5hdcFKEiCQ/gxpH5dkMLV9ZC8a+Ds9063TRzbqp2R+FDeyDZDXnOy8z+XRe2a5M6TzEjDOvymei0C06OFHmt++u/0X3c9jx0Ews2uSbDq64wGvdzK00WMOZ2iTQAndp+ppDvNtNbI5YchBnDdHM92uHNAz9fMRjCxUj2y7rhsLh2dHz2KA07r0FRPqk/VTvQ7Hbqf6jgsM/fHqFlAEWxTb4mmTD/7PLqks1J7cN20iPbippZiOCgFYfATPwcLmShGA29wG7M7f25dmi+RnrVoHUI4IYyWXEM3bwVcBFP2nCeKP2nqoS0MXw1j4f1FwJ0Mvd3QBFHkX3hD8yw970NBRcgEa7G2C1r1Cs1/E6go7JWgAW33ydykTFUSK+IDOrVLKdYDtsnBYrQptep5QQwIP2nCigLNHn1Phrt2cQZ0VNjqYh+vfclhJuRuUfp4InZ9eo1OBYYhX3otpUuPKRT/n
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
    type: Opaque