apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    discord-webhook-url: AgB1G+QOdRLKOLU7z2ulHb853yXfJVaTOi6uI5TN1wv0D+MSEvDsTfc1nn//TyMn04WWBinIW/IAjU9bNVdeRSooc5n0mU2s+be7B2dMUhnKEuMAIJSQOK4jx5T+s/1EtbxRvUHUGuDAyRAVy5PpMkGxY+7qytMdOzP4D8crZDJCe/ghoV09+6xeohnBaFzC9CkEXhW68IYYhVWt0oz9PpdNwv0VweuPtHaE9q/SYQKavz4db0LyKIVWrqyNrgGQaselylNjaxxbNwrs6iZn/f0evGb7+WaKewQTLMw0SyMPaOQ7Mn1Fv/4ybR5Qns06GccKZzcQ/2+vJgEIUKxHhdMBUfFMxRsTgvVoRUX3mCGXSIcON+rCR4+xRTN7skuOT9zN89d5wHf5eDKkEUKPs28/NDFJPIHeOXXCHdhFl0cM7mLd2iEI5wKAE4mOub/SfQpw9jN24utgQ2XyHljnamoff0xqpr8nQPvW25mOxGWXKVzg2S/P6o6q5vHrNgTWkNNXjCqcVIAeW/GgMrSt1dP2y6PlO+YSJr3WsHfQ7t3/EuL68ziscynkS3oFDtRxYnIXGfvJPYJynm/NhgfxOc+lRTIwvHlwrWQiYB0fBz6QEyXNsHTx4iqPYYvAv1ifxdk3Bq5SmPMVtD4/CSNLHJIclKcJ50kSrkxNeBjzQXuMlBI4lQvgAsUrvztw1DXx6UtZfZUNBP31zosj0t35F39VEMhd4rhhm8aybyJwCgGPNewnxuf8BC+CT5LwUZ5cwf23Yz7KNKA4H7bePNNpzzwPDzuFRXdpi/sWcaFIDPTX1LkYYNSsfqTqNgDeefMCHhNgzpZydluvYdifcOZ7CspaZ/NprnRrB75DWZT3jCPa
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
    type: Opaque