apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - uptimekuma-api-key-secret.yaml
  - uptimekuma-scrapeconfig.yaml
  - qbittorrent-exporter-auth-secret.yaml
  - alertmanager-ingress.yaml
  - grafana-ingress.yaml
  - prometheus-ingress.yaml
  - grafana-admin-secret.yaml
  - alertmanager-discord-secret.yaml
  - raspberrypi-scrapeconfig.yaml
  - uptime-kuma-secret.yaml
  - scrutiny-secret.yaml
