apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speedtest-tracker-secret
  namespace: monitoring
spec:
  encryptedData:
    APP_KEY: AgASBokAlFA83HN4sVPipFzzQO/1aQ/3fKYG65Ar/Jc3nEAtMzqd9LjrQ6TfxRaTn6MvAfXIyNMjoDTVCWHoGaEJscRRS+HgUjGiWb9ddCnP0k1294SaV/55UzMXdhL8Zm138RGlnZob3fegVLA28Q62zGzvhTkcwtkqy6jiemdso3DHaq+q19GATeEEldJzV6BH7J4hLtgbSO1yB/vqZRvmJGDXM68CPtwGzDjn1GGuGvXJLlJmdP5zQ1rDMppsJf9mglBgzJV2YBTlP5M+m5s//IB0y2uMVJ10tkstccbqS1RT5V0iyvQ0Eah3FtJOEeLcIFqHaqfCdlEb/knUgauFt/qC+ds3NGkQ5mEGDBv9kUWfAuUqaN0nluz2l+wA9Y5MN5Rh7E3pUZybNCNq1DxKncR4CCRr+evVTR3D54ViAJPzEkkDHW9g8e1VTN+1f7zQvtY+rvSgwaQ1ThDXxIwkUms3uG00iU0NDlUWqKGQ1dcZ1fd3kEo5mh0EOjmBVT8NgGM5L1jT+SWIne8X0hkdnBFRnV6G53s3MaaW++Kb5j/0wf2feXjpOFXdiFUED9Pm+a4Scs53aWNQyJCLzVoDlDxJL4tu0AVfqLgYWbV5aTURhhS+SFhBs/QgDyQBwvaDtGg6vWzKbURdkClZyl2mI7JKKSz/tm/J6tX3eS0pYPROu/V+jtDgiCDMe55Zrva7Q3A8UdPFK4NjSeRT0bP6NZuw2mF1UPgVa5ja83T/YNMVX6TS3wmQKkT7y08Gzxe/uWQ=
  template:
    metadata:
      name: speedtest-tracker-secret
      namespace: monitoring
    type: Opaque
