apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptimekuma-api-key-secret
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgAUA7b4una7sdwR02epugRb6lcx2JztkmoVGKwMHxqHaSdIGc59GFyyPzc3UZ/lPjy2G2IB/LuBm/ZBYn+K+KVMSZiSijdBkvA7F5AJUdsgtKsIdtIntueg8LaVJx2IuOoP/ycbGBSZRQgRGi6HshS4l7S1AP76QTtqOaQJXBHIcMyGwoH/h3OFTFL8A6Adg2rlDOBsgiQjdTGneIrs9Ti1tTkfL1zOM5HdVRo9i4JHAX+GwJ9OaCGwHhwm766FcU5gbe+4hE5ZQgJZJIyLZTy6mMR8K5I6dxnbuHW0G8hLQOX/8QPUluQxS5+EyuDG1IgHi3BYpGwGtvxEAjl4TIW9zEDm1pCfv88MgidZR8fkt5J7OES7j1+H6tEd7XWF5c7Wm/FOTXL5x/C+kZOzBC9dx88nhkLpVvzSjKZKTfNouqlVQOnO7LWA60aHLex9b2P3h66ASXdZUgjovd8L8CRRayBAb54j2gMZEGfYsVd8Dc56n4Khg2dLhyFlSYbft8661hsrNtsoEvjxB6I1O4hwcJnXYzq+AbTd6DQdoo1W3oaQ8rbkamMry392j1eP/wQixMETIJxp8LgYh5mk2lsWXRJbPqrqbxdOBRPWVOF2hkfmhUXPDIaWSSVo/1fZoe+xxlDNZE0cJmvii0IQVWoNElcnR3/4CecQ8mS+dsMxQwasvZtdffsD/uzkkt92Wi5zAlf2OGELWtzu7mQny4ycrjoCpZq5L5nCeLI4sDLwv7UrrOUPn5HykaqPQA==
  template:
    metadata:
      name: uptimekuma-api-key-secret
      namespace: monitoring
