podSecurityContext:
  fsGroup: 3000

env:
  PUID: "3000"
  PGID: "3000"
  TZ: Asia/Kolkata

persistence:
  config:
    enabled: true
    size: 512Mi
    storageClassName: nfs-csi

media:
  enabled: true
  existingClaim: media-vault-pvc
  mountPath: /vault
  readOnly: false

httpRoute:
  enabled: true
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  hostnames:
    - sonarr.k8s.harish2k01.xyz

resources: {}

