replicaCount: 1

image:
  repository: ghcr.io/alam00000/bentopdf-simple
  pullPolicy: IfNotPresent
  tag: "2.8.4"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
securityContext:
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  hosts:
    - host: bentopdf.k8s.harish2k01.xyz
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: bentopdf-tls
      hosts:
        - bentopdf.k8s.harish2k01.xyz

httpRoute:
  enabled: true
  annotations: {}
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  hostnames:
    - bentopdf.k8s.harish2k01.xyz
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}
