apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    discord-webhook-url: AgBo4xdCfmVfjImTdzS6kWnvGFQkh0v+lBTxUdjbOudRgZGrsLO7UfNmC5RU8WXSR5bXFkwWd3atjENCsuw2FLQiU/s77L49kJDxrOQva/cW520Bad7mbjGJ60ntNFQsTgGdOFJbItvwwPrhXNTKG+dGTB6w2SZjT5FoMRbTY84C2lkMmrxK/RkQ6kvldhP4neusS9F55/5NbU+PBFKxVMn5oEHFKZw59LPxUVDATJ2lwetlr6aCqrmIz+bs/WT828a8YoOooIaXzBLD3haI2fPs9TuPI2kOPVtLe4T/+egC4fRDh9OQhDZSXgzLU2xcoWXFejdos/CIQ/94YDySjSKGNza4O8vri+odmNxG9AMIsRqBXYSnPD48CdFYM8w8aQOa6dvbwGp3Zb7mAyWAiafukhtq8NleXHX6RctYn9n0mhveUbuTmflpuHJXt0TETGgaTiBtSVV5Nm6sEZf5Ua8fUzna0BheqqCI7fAgVKtqkJSifBwfMKzGRO+cpKann6HBqYkvI4IZyL7jclulFYWvzIlVSLyw3FJ6I95rVlLH0i467ZIo5VQ3ls2BSI6YBJvxREyFpuCWfNIldo1j1yw/rz1mv1f3/MgGLIeRwc64hBfZWeiUa13qELZXV4QWT//VtNCfQ+dMTXicybKu8wU3vh7dUNc0T+Un2oFI20jBdI8I89Vc00irH++Y2MPCnVZEthY1A88DxQh5Z8H8CM5FpMFIoAisb4GAGrjUevwbLw6IlowlxWJAzGzo0iV0izMS6zhW1L8Z+B4isUPw/F3p22Fyg3YF4GN4YXmRoqXHQhrFpX1sMHUgTfNckE0bg+E8kRf0K+7jFVGjxxjANXo0zK8FTMyAGOzZ
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
    type: Opaque