apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBeOGi2nQeX/fK8U2NI/Ycml0HG4HvU/+hurxTT4EyCEwe6pS5D3YOvPsABvw2i08Io5FcY7VrbJ/mbUI+t7TtCE7tCvtoAAcEeiFTkSLpm4hpi9YsM1MgCcu5RmZIDFRq9mBXmmFu2cENo4HARofduz1DM+fTlJYV4AfUFMDFGT3tP8hNKpXqqeDihDnNmCVN7ve1Jt6pAZMgg0hwWSr5oUpE/1BC12cELVZoXkB54KHGsqWKLlqGTWo+KTw8H11U4Ri457vR3+7q+kXEzpkbb/dq5PMJ18vPCN+vq3MP5whmLCQaF2BmXoteYPdd+bOFKa9Je+dj+beYjpYbPLbRAmaw7gqEUrbRhDmvt7X67ipISHe9WnAKC1153I7a6kg/LkWnC9YFgqhsRsMAvTJMo88T5wxdwW58CkoIxl/0wbdsaTxM5SP+ing3V+P8lCKJ3aU8WnWxoueG8/KYbIpmsnBpll6sZ/bB47o6jN82MuEbb4h7UrN6hc8FYhqUy1fjLoeBDlxWh7Ydy9hB7zdWShhmicIm8KwxQ/ZDSWqe8upoSi1B1nxp5zrjvmufcBxUUDmNLy+seigvx4ti0xvYVM04i8FvZbmt5G9KEjiWHA23ddqjUKygsq9GNQljGwC5btwvDflpPal/l/0Y2wGUSV1u2dahpOl5pgN9d9LaChdjrSQ4RTaAeDnxniurnUjLCN5Ywx+wQxc3AtH4Q
    admin-user: AgCIEjERzqQEAflbiqSToJl+dgTRRJajs4Y+tHVCsMKxSIo6CkVHMwhA36pWel1a/K64d+Kx4/BiE1uc6VIbWvOMJ0oNAan4kzffnQqO9mRMhM5j/xgsmey3hGniHXWR30ZFa/Kg3r9AazZfxdi3tL9Cv3i+aGiH328gIqIHolgvK4JuqQ+HIy6HP7nA4o3A7QCXYMZUq04Rlo4JLLeh6du5+4xsNPNWnTvC2wn31U2ygVmZgQjXFKR394SVW5ABCbwjannPgbMEpAhIytmWegqI7woDOf7eWV93lJqf5oyHM/bbVjXAO8PQ+s7Cfgip5OTfHxrL/6fkruiT/NFYlMIyelWjk/YZceBV5MgrX83CkC9L2aelMMHJtTTZkd14KyPLqN79mmnfmo6H0vBlgLo5K4K+5PwWpF8XNH77oOR4GqtLWxdMrruNpC7imtiCoFEfyEHapTR46W5aFH1tYjmfzWcjg50YVsaOOMm7AqEKuyqHB0XLpBZOKkOPP88DbvZKVKqV1xFbHIjsFhRwjD05MjdF3PDoIEhG2Qpvtweay2hmtHGmJVuVeFHLZQIc9pBJtVpnofjl1PDd5/J2dCFuKcxaUfJ346Dydgrb6G1hYPg3Tysz0n+Ml5eAcGbngfMZmFKRWB+GuqNUPkbw/Sjis0bvuc3YTsL/zzkHCFffAF1kwYGs6EUhCPuKiEmZH8LoM2TFWg==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
