apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager-discord-secret.yaml
  - alertmanager-httproute.yaml
  - grafana-admin-secret.yaml
  - grafana-httproute.yaml
  - prometheus-httproute.yaml
  - raspberrypi-scrapeconfig.yaml
