apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager/
  - argocd/
  - grafana/
  - longhorn/
  - monitoring/
  - prometheus/
  - alertmanager/
  - metallb/
  - traefik/
  - headlamp/
  - actions-runner-controller/
  - cloudflared/
