image:
  repository: prompve/prometheus-pve-exporter
  tag: "3.8.2"
  pullPolicy: IfNotPresent

proxmox:
  # One or more Proxmox API endpoints to scrape.
  targets:
    - 10.10.10.100
  config:
    existingSecret: pve-exporter
    secretKey: pve.yaml

service:
  type: ClusterIP
  port: 9221
  targetPort: 9221

serviceMonitor:
  enabled: true
  interval: 15s
  labels:
    release: kube-prometheus-stack
