apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bazarr4k
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://harish2k01.github.io/helm-charts
      chart: bazarr
      targetRevision: 0.1.0
      helm:
        releaseName: bazarr4k
        valueFiles:
          - $values/charts/bazarr4k/values.yaml
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3

