apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: cert-manager
  source:
    repoURL: https://github.com/harish2k01/homelab-ops.git
    targetRevision: main
    path: cert-manager
    helm:
      valuesFile:
        - 'values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
