apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd

spec:
  project: default

  sources:
    # 🔹 Upstream Helm chart
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.20.0
      helm:
        valueFiles:
          - $values/charts/cert-manager/values.yaml

    # 🔹 Your Git repo (values source)
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  revisionHistoryLimit: 3
