apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd

spec:
  project: default

  sources:
    # 🔹 Upstream Helm chart
    - repoURL: https://cloudnative-pg.io/charts
      chart: cloudnative-pg
      targetRevision: 0.28.3
      helm:
        releaseName: cloudnative-pg
        valueFiles:
          - $values/charts/cloudnative-pg/values.yaml

    # 🔹 Your Git repo (values source)
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-pg

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  revisionHistoryLimit: 3
