apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  source:
    repoURL: https://github.com/harish2k01/homelab-ops.git
    targetRevision: main
    path: charts/gateway-api

  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-api

  syncPolicy:
    automated:
      prune: false
      selfHeal: true

    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion
        - /status
