apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd

spec:
  project: default

  sources:
    # Upstream Helm chart
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.34.0
      helm:
        releaseName: vault
        valueFiles:
          - $values/charts/hashicorp-vault/values.yaml

    # Git repository containing the values and HTTPRoute
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      ref: values
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      path: manifests/hashicorp-vault

  destination:
    server: https://kubernetes.default.svc
    namespace: hashicorp-vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  revisionHistoryLimit: 3
