apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd

spec:
  project: default

  sources:
    # 🔹 Upstream Helm chart
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 82.13.1
      helm:
        valueFiles:
          - $values/charts/kube-prometheus-stack/values.yaml

    # 🔹 Your Git repo (values source)
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  revisionHistoryLimit: 3
