apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-next
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://harish2k01.github.io/helm-charts
      chart: portfolio-next
      targetRevision: 0.1.0
      helm:
        releaseName: portfolio-next
        valueFiles:
          - $values/charts/portfolio-next/values.yaml
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
