apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/harish2k01/homelab-ops
    targetRevision: main
    path: charts/qbittorrent-exporter
    helm:
      releaseName: qbittorrent-exporter
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
