apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://harish2k01.github.io/helm-charts
      chart: qbittorrent
      targetRevision: 0.1.2
      helm:
        releaseName: qbittorrent
        valueFiles:
          - $values/charts/qbittorrent/values.yaml
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
