apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smartctl-exporter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-smartctl-exporter
      targetRevision: 0.17.1
      helm:
        releaseName: smartctl-exporter
        valueFiles:
          - $values/charts/smartctl-exporter/values.yaml
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      ref: values
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      path: manifests/smartctl-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: disk-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
