apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://SonarSource.github.io/helm-chart-sonarqube
      chart: sonarqube
      targetRevision: 2026.3.0
      helm:
        releaseName: sonarqube
        valueFiles:
          - $values/charts/sonarqube/values.yaml
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      ref: values
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      path: manifests/sonarqube
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
