apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://harish2k01.github.io/helm-charts
      chart: syncthing
      targetRevision: 0.1.0
      helm:
        releaseName: syncthing
        valueFiles:
          - $values/charts/syncthing/values.yaml
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      ref: values
    - repoURL: https://github.com/harish2k01/homelab-ops
      targetRevision: main
      path: manifests/syncthing
  destination:
    server: https://kubernetes.default.svc
    namespace: syncthing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3
