apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDDR4vBMqbWGLQ7ywmrffzGZlGUarguWZKuDXpuL8oi9twuei5JzUBp7XIthy4rPVS6lcZRg5lkjUl9a4VYVYZyR04x8wwubU1D48jBiIcQJ+Cm+Hv4afWO0ad7px9z6rY3KLqtaJh2OHfovlczAfgO4dMBBBQHZ5y2JK84OKrKeVzzM98g1QChKhJh6HkAapQUrVbuZOme7ay7T+YAglKH/t0mW1YrgqqGqc9l5gAGvaUTSspF691RuLJbimkOFw+GxAs5vj75yXMjjXgTnx/+83yMm6sakxKaNnMjAJVhgdg9MOcxe7HZxnIQSNC20JueWmA5uZDQhAAm2qvHvAOD8dC3TXEPkoTBvx4kxTIPNCr9yuj1lWofj0ZyijXGGXeE2dIBaOPQMtkWN+6cQ66vQwIiU8MLDGVc8BmzKDxi2KwXUbe+P2pJUnp3f+D57YjRomFxiIKFgdh9PNPLY/D8+sHQ7DXAvVblGwotlDANpE0mgYBCJ4hH+hig16/Y5SZ3jFZ54l6dnrxTgiAV7eNAooFLAI7UEgRr63ee5Btru4I5zXBXvzrbgZ3CiGQx0jhugF/3+T/mUq+WzOJXHHSiJ8TYDENMOgdBN2knsl7g5XSluC6MnXM8Ip1DircOKJGwJituEqyCrViMQwZ51K1+Aud+sQJxm/ZunPCSk16GwQAsBN6YOpSyth2SyCW7JwrNc1EBZG0De0g8XOoW3TISlgh4hAk3TeEnY+Cvrbn/PvVraGj72q3f
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque