apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-vault-pv
spec:
  capacity:
    storage: 1Ti
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: media-vault
    volumeAttributes:
      server: 10.10.10.104
      share: /mnt/MasterPool/Vault

