apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-vault-pvc
  namespace: media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: media-vault-pv

