---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: umami-app-secret
  namespace: umami
spec:
  encryptedData:
    APP_SECRET: AgCPPbHr4ygHcq8EOfcgyes5Jxca3puGAJk/HUdjpsTZ39oyGy5eyn/0oKwMrAePG7s0MkcgdpWXWfVnec1tPbJfG/ORbN6CVRqwQpNFlFXvoBjOCSPTTtKl52cTtgGplVvci8+9NoqoL1K1WqrXPkqIVSWLhiJJC7pnFTf6vhpMh5v8/nTrc75WfHjdNW2M4NxZd8VzUbAIbj5F45DjPYFNt4obgMNPYD5xkpCbNxeNCAlIVjr+Y6r4kihsVZ74cVsAHNQ4xGOgjRTj8fxniY/Y9/SynHdIIfNSCNeKkqeFYZSITzp9Yim8rV5sMx10lzRf2QnSuykC8/8X8pIXufT4bCUShaWihuK/MxXRDC1BddHaFE+hH1n25+5mQctS+ZO8paiTaO6iZppZ99yKdUMtEHbh4R/OhTSJt8HQqU/pc/wFWDkx9lzGTqZ3GYb6sCA9KV+9ysCnpiOUQihhTnPLf5+v06/IFA74jiMkxookthDdPb+1C4/NAoWSLtWr7EAHGP04C9rmr3L93FZguony7kXDnf4xc1RbajHSojE53ZS57qCLv1dAg48lYoDl2XfEnBvuCsTNbxEFt4i8Wl/Li1GRkP8YldgWpwlcan5gBL5pMrv8tlQ667MDAVUHi3w0XZH96B0EVmIxqDf6Hb9F2zFNY1jcviy4mV0j2qMtfjxY7xrg8Zkge+r4JCPZjb5XUhv9LwLwJNuVw9J0dD5Ak9orVqILNULaWUIc9mjV
  template:
    metadata:
      name: umami-app-secret
      namespace: umami
    type: Opaque
