apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - media-pv.yaml
  - media-pvc.yaml
  - library-pv.yaml
  - library-pvc.yaml
  - immich-db-secret.yaml
  - pgsql-cloudnative.yaml
  - immich-traefik-route.yaml
