apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: rpi3-scrape-config
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  staticConfigs:
    - targets:
        - 10.10.10.106:9100
      labels:
        instance: rpi3
        device: raspberry-pi
