apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth-secret
  namespace: tailscale
spec:
  encryptedData:
    TS_AUTHKEY: AgCSBYFVWrzMF0m2Kfg6mOnnUxy2w8Hn+WnrCJHQr9w6KsT0EojIFxr08xaF0frrq2GZxMjMo5IXMtnrxSQqlOgo0XZ7Ti/VIn+buInmq/ncQjLje7D1CwNq1ImR+MIko9so4AFmP/FhFB59zOqKr3OaM01udyM1W0aWGKEKPYyGEL7Izj8Nm/Od6MO81tNIml0d+ozI5FyZCmQq4g9GJidsrT6VCbd6inOW9Er/ViHJrdkBE+LjTnLxbi3AVyh+kbu4lKsFBdWX4W3lUvUMK/y7c73Ofi4s7eqUmkxOp/ljBxEc8Zaz1Gbuti9ek4+w5g9xJT8LjRGR0hdHo+H9kSZiVhrGXbXNhR7pZ59j6Nits+IEj0OmSOdcovbmto0EjnlJv/gO0k5ZfXBXJ23nkbO978pcIaEYJQ9qlrsJPt6SRAqf4k5sX5uhAoSwwr7LUn+MpoC/mHu4ero8XFrph5Nz6XlhkWw1v98pugXhqRKjjqq9WHpU5Z+CEtZnU3+xaMnHtfwz1xbU1FKv4WQdkgY2SlTbCyfHip5MKC+rcoXgikvTtdf64NoWSsDY1amIkmXBsi8qDJpiPtS60Ctxpr8vi8ipEFZDE9RIXkSjSUTnCMZS6Bq2D/8Uv3AZtCYnnNWCNSLWl1bxK8GsTViP6Nk+VjY5xTdnZmlcx9kPqSxZQw+jAscm+ryrm6elH8cYUDQsh6VNKFw+npqSrKTpC3PwMR8tOyzv5hmDu8YcRob/cfhdXwJ4nHo9G+/jvZSo7/hoMjqUmumImCHYZ7snKw==
  template:
    metadata:
      name: tailscale-auth-secret
      namespace: tailscale
    type: Opaque