apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-warehouse-pvc
  namespace: syncthing
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: syncthing-warehouse-pv
