apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-warehouse-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: syncthing-warehouse
    volumeAttributes:
      server: 10.10.10.104
      share: /mnt/Personal/Warehouse
