podSecurityContext:
  fsGroup: 1000

env:
  PUID: "1000"
  PGID: "1000"
  TZ: Asia/Kolkata
  WEBUI_PORT: "8080"
  TORRENTING_PORT: "6881"

persistence:
  config:
    enabled: true
    size: 128Mi
    storageClassName: longhorn

media:
  enabled: true
  existingClaim: media-vault-pvc
  mountPath: /vault
  readOnly: false

httpRoute:
  enabled: true
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  hostnames:
    - qbittorrent.k8s.harish2k01.xyz

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 1Gi
