---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-secret
  namespace: ghost
spec:
  encryptedData:
    mail__options__auth__pass: AgCWrlOzMk3YCRKDwThQpV3Xrqwl7Qoz8gupZgzrAVEIo/diMHdJyisKMWUl5sTXPlDNV6Jg3UU5Hn6OZsgfPs/a+ccND+oi2nByrml4LAhJcF9CJK0GzTXpCoHndf6kVHevID0rtpgLk4+W1T2cyTluMdg6Ax/eYIoXKjXuTy8drc7Xz9A/ABmbkI1b9/cl/ZbgnjahbSexBFZGNuBl71TEE49Qyty8TXSjTiVaeV7wUAoGaqkejEaF+WSfwMk1Kl3K/M3LIJUnCBm1WlUMIRgz8fPOCYFuANJcGn3hQlatFwgDJOABnOrGxGyfI1aYCeeSsv3ZK6lXlM+4r3dxQ3Vdfabht9aFSpQc6fOMx9QSGZM/YutI0JFdnPaSmgoa/h/mS8iMOAsx0rimY7ORm8BQNHnTQbTG/2ZMP2ze3fZsdwXR2lZfsMM7vj67tARmppUlZyQmG4R4mlJpSlxFvoKb4+uIsNlVEhi8MrWM2lWaztTvLWvf3G2DlFRIAwgLh9wwOamkBXa20CtMmAqTFIeYxJJIXevCAbHBYga42KQQE1yARUFRNq7m5H5J4K+o9v2LeZ31oM08O4woHKmsgSyvtiRWlAWdud+Xhkg1T8qxzyPMhZjOxvjwf3eGVRZoWGO1mgNeuDwoW4EYG7W3u29FkFEjP7CIhzC5RQvHp4fDG5JD32qOBgKYVdMuak0+yWHIqZrv1FgdteltY3gc7pnWNCSh
  template:
    metadata:
      name: ghost-secret
      namespace: ghost
    type: Opaque
