---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-mysql-secret
  namespace: ghost
spec:
  encryptedData:
    db-password: AgB2DcHWhytBHznx+wsc/Ljz356z6niYFUrs0cTuxpQXbqvqBCRxY8NPUDTJTiA8SCW0HPZxlxKqwBEFsiwnNTKbIWC974oGGV8RLPJSqKsIBN6iFTJCR+uWNsCsIFPL/oyP4iXiEgyiyaa25yjcstKbxuB4l8WQFJFel3APsmMop1o9ETFi7Q3Tb9IJVdOOXaW1wbco5QLXK4NYgapk5WeLuAFHo/m70fXqsTiIcB4kFSKkZ/pvNP3+Ngs4awJR7UkbcyOvarwxXe7ontRwFH+1BuOrcmw4rbyMfasMnqeBHJGVZRwQrKeypHxQRN/R7MmJf75si55F9AQC2CM3CuU4wBuOtc7TPZl7rWyaYu9E/cCiDoiVee7ddlOFFBuT9TawcBu8DJhXEbyGPHLdvInSQhgTd3Sji9UDrsBHkOg86tV0wvgU9kz0hHH2Z/u1Oyt7LNkgYY2APKKnX1Lj+u/nGRBBZT2fyPAH1JrSZV1E+j8m/IEUD3AH9RF5MvxL/UGte+X3iS2QpJiG7/N+JB11qsEXC1m3jDECfNfqP+27L2rphFo7LFswdZV3Fqb2T+9aClY0vWZQ2OGveLOI/5yH1z+ngNKIPm/lkkJoBAUInNregH+8WSeSeuSIluT+vrL5J6uSY+wMw7xhCR/THgIr9Id7NFIINZm/MkEr7J27nXzom/WeZxBLiYtVFdSmLMhbsGWyJKgt4g==
  template:
    metadata:
      name: ghost-mysql-secret
      namespace: ghost
    type: Opaque
