{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "pve-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    pve.yaml: {{ .Values.sealedSecret.encryptedData.pveyaml | quote }}
  template:
    metadata:
      name: {{ include "pve-exporter.fullname" . }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
