apiVersion: v1
kind: Service
metadata:
  name: {{ include "pve-exporter.fullname" . }}
  labels:
    {{- include "pve-exporter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pve-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 9221
