{{- if .Values.servicemonitor.enabled }}
{{- $root := . }}
{{- $targets := $root.Values.proxmox.targets }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pve-exporter.fullname" $root }}
  labels:
    {{- toYaml $root.Values.servicemonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pve-exporter.selectorLabels" $root | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ $root.Release.Namespace }}
  endpoints:
{{- range $target := $targets }}
    - port: http
      interval: {{ $root.Values.servicemonitor.interval }}
      path: /pve
      params:
        module: [default]
        cluster: ['1']
        node: ['1']
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: __param_target
          replacement: {{ $target }}
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: {{ include "pve-exporter.fullname" $root }}.{{ $root.Release.Namespace }}.svc:{{ $root.Values.service.port }}
{{- end }}
{{- end }}
