{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "firefly-iii.fullname" . }}-cron
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  timeZone: {{ default .Values.firefly.env.TZ .Values.cronjob.timeZone | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "firefly-iii.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          containers:
            - name: cron
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
              command:
                - /bin/sh
                - -c
                - curl --fail --silent --show-error "http://{{ include "firefly-iii.fullname" . }}:{{ .Values.service.port }}/api/v1/cron/${STATIC_CRON_TOKEN}"
              env:
                - name: STATIC_CRON_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "firefly-iii.fireflySecretName" . }}
                      key: STATIC_CRON_TOKEN
              {{- with .Values.cronjob.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
{{- end }}
