{{- if not .Values.firefly.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly-iii.fullname" . }}
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.firefly.secrets.inline }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}
