{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "firefly-iii.postgresServiceName" . }}
  labels:
    {{- include "firefly-iii.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/component: postgres
    {{- include "firefly-iii.selectorLabels" . | nindent 4 }}
{{- end }}
