---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: umami-postgresql-secret
  namespace: umami
spec:
  encryptedData:
    db-password: AgBiMlwG+x6hrmby29N4ZlPC7A4s6J72vPvj4YbixTlC3itefJxchTSjlAxw4Eph8JYzuKUS2VkyX0qwsWswVDv2c+0sh2Ck56HtG/NWNvIX702DNJMEl1Nj/Ls46OhcNJ2w+z2KQXsyCOLOQiwCaVMRn1Q7kKI8bIs2gGVCtUdzVh0yOKN0Z+XXh0SZXJfoRvM25NOdIIgb91nZMm+FmEGRAlwSC99r6Zjc5LHEyUe4rQAhEX76F16I5lmyhgp9geoiJobwSi7WDi8hl7EJK1ro/rxfAy8jpJzRHqVq0Hh73hYJtACljrH9uuNnS8b3CXvq5cbpMXGGhliFeAQOkwarzJ0a62rCX2DMLql0uc2jfa3HPvy20W5TbqLPVt6DhA5s04erQAM+yQPi4mH+bcK/eGWwmtbBuuT6VjkTXr0r4Fqy5Xw6EfRSMz81duJeZ8pKTIVojABBRTtHqkBHirVg6XyXShINbM1ql5YpZb2Ejft+RfHufAr1X4zFrJxIOKV9csNS0Npnj1gGI/RgRDB2aVTtGnLqqFKlD8NZxRp8HhxZIRQiEeUg+beSCsAmuNAvp9s4LIp4tr9INJzqCBEmF811ZWoPVXz3JvPOUYv3YyxoCtYstlt54J3aLglddvlQ9AsjXLFXtop6IuDgRzsKZofVeejt8xjwKQp+DRmwKDNvzSsCit/ZCXu5JOX3pkaOmlJDpg==
  template:
    metadata:
      name: umami-postgresql-secret
      namespace: umami
    type: Opaque
