apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent-exporter.fullname" . }}
  labels:
    {{- include "qbittorrent-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "qbittorrent-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qbittorrent-exporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: qbittorrent-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: QBITTORRENT_BASE_URL
              value: {{ .Values.qbittorrent.baseUrl | quote }}
            - name: QBITTORRENT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "qbittorrent-exporter.secretName" . }}
                  key: {{ .Values.qbittorrent.usernameSecretKey }}
            - name: QBITTORRENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "qbittorrent-exporter.secretName" . }}
                  key: {{ .Values.qbittorrent.passwordSecretKey }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
