{{- if and (not .Values.qbittorrent.existingSecret) .Values.qbittorrent.username .Values.qbittorrent.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qbittorrent-exporter.fullname" . }}
  labels:
    {{- include "qbittorrent-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.qbittorrent.usernameSecretKey }}: {{ .Values.qbittorrent.username | quote }}
  {{ .Values.qbittorrent.passwordSecretKey }}: {{ .Values.qbittorrent.password | quote }}
{{- end }}
