apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgAgHw12oWMnnthvKFPRmWjQ+LgesuYtHEU8f069fYLURd1p5U0AgN1sz/M1TnkG3+D2LAjr9oGRD/PSKdSZnYDWqHXEHOIAZJOYko3u0wtcE5Ne100viAF2sDQu7pK4oGrprfe1jpjZuVSMEmWnkAJgb3rnfIl1i26Xu95kpbI7xxP72m4F2DyrOxKin0Bu5hswhlYuLOMXPaCVdWxrWYccEHlv3PKhJGFozclpkLu3a+ezWJdhpsL4A1C/UwVR52B2urlNJRAcVkVLMxQebAkKlR/wtrj2/QWcDS1+tbVsM9L4u0o+FwGQIchLAOITvanE2fJus+Sc+GaYNpid/CujvKBQN3pChzXUIoMcf42JRww7lRvlXGQc1CioOOaQX4+/Z006gw2b7Rqb7ozIISL/YZNriXycroMYjNSmrjgtU0a4Gkj8tJr5T7wXJCh/GXH0cbmuT12XYwFI4KJND5efQSIdh1tlRt/I7JUGyxPRnfvTLsxGK5bwtaDudgJec0GMxOWY4zFsTKLlNrfKyGgCZeL9kotoQv6RrjEpqXf6EQH2VnysbzimEFC3biTl/qOKZnvyl9fOWEEAjsITehYSGrETzN25xVe/SxtGof3ZQQmIXAhk96zXDYXUrcIl5fPYhLoaKBGvsQyzHWSLPOBtcnn9FSoogTUar/jHg2JmcemJ/NzYFXXVP88kIuveriUkMJrqYiymfjGt/8z7iDAaZCFxx8RCDG+Hl+MhpNg8RUm19iXcRT5n7aQQPFuVWjw4JCATmVxHsSZwBGSWx1ekHaE9xERgREN6kJ44ORM2bx0grja1HyVhpfg7aMrMh6buLqYyXAeT8LQRqYDt2lvtW9QhdESmAL3Sd4m6/D/S9ZCJFtnp+JClLWJe6zEDikxT2p1alOwAfbNSRQ9fuMj9kNMv89w983oBuvTI9toy/WT36b8xxZnK
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare
    type: Opaque