podSecurityContext:
  fsGroup: 1000

env:
  PUID: "1000"
  PGID: "1000"
  TZ: Asia/Kolkata

persistence:
  config:
    enabled: true
    size: 256Mi
    storageClassName: nfs-csi

httpRoute:
  enabled: true
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  hostnames:
    - prowlarr.k8s.harish2k01.xyz

resources: {}

