name: Update App Version

on:
  workflow_call:
    inputs:
      runner:
        required: false
        default: homelab-ops-runner
        type: string
      app_name:
        required: true
        type: string
        description: "Name of the app"
      image_tag:
        required: true
        type: string
        description: "New image tag to update"
    secrets:
      GH_APP_ID:
        required: true
      GH_APP_PRIVATE_KEY:
        required: true

env:
  OPS_REPO: harish2k01/homelab-ops
  CHART_PATH: charts/${{ inputs.app_name }}/Chart.yaml
  VALUES_PATH: charts/${{ inputs.app_name }}/values.yaml

permissions:
  contents: write

jobs:
  update-app-version:
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: harish2k01
          repositories: homelab-ops

      - name: Get GitHub App user info
        id: app-user
        run: |
          login="${{ steps.app-token.outputs.app-slug }}[bot]"
          echo "login=$login" >> "$GITHUB_OUTPUT"
          echo "email=$login@users.noreply.github.com" >> "$GITHUB_OUTPUT"

      - name: Checkout homelab-ops
        uses: actions/checkout@v4
        with:
          repository: ${{ env.OPS_REPO }}
          token: ${{ steps.app-token.outputs.token }}
          path: ops

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update image tag in values.yaml
        run: |
          cd ops
          FILE="${{ env.VALUES_PATH }}"
          NEW_TAG="${{ inputs.image_tag }}"
          yq -i ".image.tag = \"$NEW_TAG\"" "$FILE"

      - name: Update app version in chart
        run: |
          cd ops
          CHART_FILE="${{ env.CHART_PATH }}"
          NEW_VERSION="${{ inputs.image_tag }}"
          yq -i ".appVersion = \"$NEW_VERSION\"" "$CHART_FILE"

      - name: Commit and push changes
        run: |
          cd ops
          git config user.name "${{ steps.app-user.outputs.login }}"
          git config user.email "${{ steps.app-user.outputs.email }}"
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git add .
          git commit -m "chore(${{ inputs.app_name }}): update to version ${{ inputs.image_tag }}"
          git push
